CREATE TABLE IF NOT EXISTS Todos(
    ID INT NOT NULL UNIQUE AUTO_INCREMENT,
    Text VARCHAR (255) ,
    Done VARCHAR (6) ,
    UserID INT ,
    FOREIGN KEY (UserID) REFERENCES Users(ID) ,
    PRIMARY KEY (ID)
)